spring:
  datasource:
    url: jdbc:mysql://localhost:3307/practice
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1051452053286-hehs3hhndsaahk0ik6bno5nn21uh0950.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8000/login/oauth2/code/google
server:
  port: 8000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days